<a href="https://colab.research.google.com/github/sydoky/Artificial-Neural-Network-ANN-/blob/main/Artificial_Neural_Network(ANN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [2]:
tf.__version__

'2.7.0'

In [3]:
dataset=pd.read_csv("/content/Churn_Modelling.csv")

In [4]:
dataset

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [5]:
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [6]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [7]:
y

array([1, 0, 1, ..., 1, 1, 0])

# **Encoding Categorical Data**

# **Label Encoding The "Gender" Column (conversion yes or no)**

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [10]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

# **One Hot Encoding the "Geography" Column (conversion multiple things)**

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("enconder", OneHotEncoder(),[1])], remainder="passthrough")
X=np.array(ct.fit_transform(X))

In [12]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

# **Splitting the Dataset inot The Training and Test Set**

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

# **Feature Scaling**

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

# **Building the Initializing the ANN**
# **Initializing the ANN**

In [15]:
ann=tf.keras.models.Sequential()

# **Adding the Input Layer and the First Hidden Layer**

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

# **Adding the OutputLayer**

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# **Training the ANN**

In [19]:
ann.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

# **Training the ANN on the Training Set**

In [20]:
ann.fit(X_train, y_train,batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6629 - accuracy: 0.6283
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4923 - accuracy: 0.7966
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4523 - accuracy: 0.8021
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4287 - accuracy: 0.8105
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4119 - accuracy: 0.8198
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3988 - accuracy: 0.8266
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3864 - accuracy: 0.8328
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3746 - accuracy: 0.8400
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3642 - accuracy: 0.8465
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3566 - accura

# Predicting The Test Set Results

In [31]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# **Confusion Matrix**

In [32]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1503   92]
 [ 191  214]]


0.8585